# Generated by Django 2.0.5 on 2020-02-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200229_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='accrual',
        ),
    ]
